module.exports = {
    FETCHING_DATA: 'FETCHING_DATA',
    RECEIVED_LISTS: 'RECEIVED_LISTS',
    RECEIVED_LINKS: 'RECEIVED_LINKS',
    UPDATE_LIST: 'UPDATE_LIST',
    UPDATE_TOKEN: 'UPDATE_TOKEN',
    LOGGED_IN: 'LOGGED_IN',
    SAVE_ENTRY: 'SAVE_ENTRY',
    ENTRY_SAVED: 'ENTRY_SAVED',
    ADD_ENTRY: 'ADD_ENTRY',
    EDIT_ENTRY: 'EDIT_ENTRY',
    NEW_ENTRY: 'NEW_ENTRY',
    USER_CREATED: 'USER_CREATED',
    CANCEL_EDIT: 'CANCEL_EDIT'
};
